version: "3.8"
include:
  - proxy.yaml
services:
  mysql:
    image: mysql:8    
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
     - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
      
  web:
    image: python_app
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    networks:
      backend:
        ipv4_address: 172.20.0.5
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
  